### ISSUE TITLE
How to use the data for training different tasks

### ISSUE THREAD

**Issue by jingliang95** [alexsax/taskonomy-sample-model-1#2]
It is very confusing to use the dataset. Could you provide more details how to load the ground truth for different tasks?
For example, some ground-truth masks are black. Some masks (like depth) are very strange. 

To make others easily use the dataset, I think more details are needed.

**Comment by alexsax** [comment]
The images are stored as pngs, and so you can load it with any PNG loader such as PIL. The conventions for each task are the same as those used in the [2D3DS dataset](https://github.com/alexsax/2D-3D-Semantics).

Some labels have mostly very dark pixels, because the values there are small. The depth images encode missing values encoded as maximum range (128 meters, pixel value = 2^16 - 1), so you probably see images that are mostly quite dark with white spots that indicate parts of the mesh that are missing. You can generate a mask by simply running `valid_pixel_mask = depth_image[depth_image<> 0.99]` (assuming you've mapped the image to be between 0 and 1).

At some point in the future I might release a data loader, but if you write one in the meantime then please do issue a pull request!

**Comment by amir32002** [comment]
@jingliang95 also, FYI this page is not about the "dataset". This is a small sample of the data. As the instructions in the readme of this repo and [this page](https://github.com/StanfordVL/taskonomy/tree/master/data) say, to receive the dataset, users need to send a request and accept the terms.

**Comment by jingliang95** [comment]
@amir32002 I am confused again. Isn't small sample of the data actually **part of the whole dataset** (for one building)? If yes, this page should be at least about **part** of the dataset.

**Comment by amir32002** [comment]
Please see the instructions. The following are the first lines of the readme.md of this repo. 

**_Sample** model: Cauthron
**A Model, selected at random, from the dataset** of the paper Taskonomy: Disentangling Task Transfer Learning. **See the main repository of Taskonomy dataset for more details about the full data [here](https://github.com/StanfordVL/taskonomy/tree/master/data)**.

**This is only a single model (a small fraction of the dataset) as a sample.** The full dataset includes > 4.5 million images from > 500 buildings with a similar format. Each image has annotations for every one of the 2D, 3D, and semantic tasks in Taskonomy's dictionary (see below)._

https://github.com/alexsax/taskonomy-sample-model-1

**Comment by amir32002** [comment]
Please see the instructions. The following are the first lines of the readme.md of this repo. 

"**Sample** model: Cauthron
**A Model, selected at random, from the dataset** of the paper Taskonomy: Disentangling Task Transfer Learning. **See the main repository of Taskonomy dataset for more details about the full data [here](https://github.com/StanfordVL/taskonomy/tree/master/data)**.

**This is only a single model (a small fraction of the dataset) as a sample.** The full dataset includes > 4.5 million images from > 500 buildings with a similar format. Each image has annotations for every one of the 2D, 3D, and semantic tasks in Taskonomy's dictionary (see below). "

https://github.com/alexsax/taskonomy-sample-model-1
